config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'users/omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'users/omniauth_callbacks#setup'
  end

  get '/user/:username' => 'users#show'
  
  resources :pins, only: [:index]
  resources :user, only: [:show] do
    resources :pins, only: [:index, :create, :new, :destroy]
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  validates :url, presence: true
  validates :title, presence: true
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # before_action :authenticate_user!
  before_action :load_user
  before_action :authenticate_user!, only: [:new, :create,:destroy]

  def index
    @pins = @user.present? ? @user.pins : Pin.all
    # selects pins that are left without a user, db trash
  end

  def new
    @pin = Pin.new
  end

  def create
    current_user.pins.create(pin_params)
    redirect_to user_pins_path
  end

  def destroy
    @pin = @user.pins.find(params[:id]);
    @pin.destroy
    redirect_to root_path
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :url)
  end

  def load_user
    if params[:user_id].present?
      begin
        @user = User.find(params[:user_id])
      rescue ActiveRecord::RecordNotFound
        @user = nil
      end
    else
      @user = current_user
    end
  end

end

app/views/pins/index.html.erb
<% if current_user %>
  <% if @user != nil %>
    <% if current_user.username == @user.username %>
    <h1>Your board of Crazy Pins</h1>
    <!--
      TODO:
        customize heading to include user's name
        catch: twitter auth doesn't include user's email
    -->
    <% else %>
    <h1><%= @user.username %>'s board of Crazy Pins</h1>
    <% end %>
    <% if !@pins.empty? %>
      <% @pins.each do |pin| %>
        <div class="text-center thumbnail">
          <div class="responsive-img">
            <%= image_tag pin.url %>
          </div>
          <p><strong><%= pin.title %></strong></p>
          <!-- TODO:
              fix unauthorized deletion of pins
          -->
          <% if current_user %>
            <p><strong><%= current_user.email %></strong></p>
            <% if current_user.id == pin.user.id %>
              <p><%= link_to "Delete", user_pin_path(current_user.id, pin.id), method: :delete %></p>
              <p><%= "#{current_user.id} #{pin.id}" %></p>
            <% else %>
              <p><strong><%= pin.user.email %></strong></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      You have no crazy pins.
    <% end %>
  <% else %>
    <h1>The user you are looking for does not exist.</h1>
  <% end %>
<% end %>

app/views/pins/new.html.erb
<h1>New Crazy Pin</h1>

<div class="form-container">
  <%= form_for @pin, url: user_pins_path do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, :class => "form-control" %>
    </div>
    <%= f.submit "Create Crazy Pin",  :class => "btn btn-primary" %>
  <% end %>
</div>